In [23]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [24]:
dados = pd.read_csv('cape_exterior.csv')

# print(dados.head())
dados.columns

Index(['Unnamed: 0', 'index', 'ARTICULADOR PEDAGÓGICO', 'Ano',
       'CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA', 'CÁTEDRA',
       'DOUTORADO PLENO', 'DOUTORADO SANDUÍCHE', 'Doutorado',
       'Doutorado Sanduíche', 'ESCOLA DE ALTOS ESTUDOS', 'ESPECIALIZAÇÃO',
       'ESTÁGIO DOCENTE', 'ESTÁGIO SÊNIOR', 'Especialização', 'Estágio Sênior',
       'GRADUAÇÃO', 'GRADUAÇÃO PLENA', 'GRADUAÇÃO SANDUÍCHE',
       'Graduação Sanduíche', 'MESTRADO', 'MESTRADO PROFISSIONAL',
       'MESTRADO SANDUÍCHE', 'Mestrado', 'Mestrado Sanduíche', 'PIDRH',
       'PROFESSOR/PESQUISADOR VISITANTE', 'País',
       'Professor de Educação Básica', 'PÓS-DOUTORADO', 'Pós Doc',
       'Total Linha'],
      dtype='object')

In [25]:
bolsas_byYear = dados.groupby(['Ano']).sum()
bolsas_byYear

,Unnamed: 0,index,ARTICULADOR PEDAGÓGICO,CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA,CÁTEDRA,DOUTORADO PLENO,DOUTORADO SANDUÍCHE,Doutorado,Doutorado Sanduíche,ESCOLA DE ALTOS ESTUDOS,...,MESTRADO PROFISSIONAL,MESTRADO SANDUÍCHE,Mestrado,Mestrado Sanduíche,PIDRH,PROFESSOR/PESQUISADOR VISITANTE,Professor de Educação Básica,PÓS-DOUTORADO,Pós Doc,Total Linha
Ano,,,,,,,,,,,,,,,,,,,,,
1998,406,406,0.0,0.0,0.0,0.0,0.0,1088.0,392.0,0.0,...,0.0,0.0,18.0,0.0,0.0,0.0,0.0,0.0,266.0,1867
1999,1134,351,0.0,0.0,0.0,0.0,0.0,1088.0,499.0,0.0,...,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0,256.0,2197
2000,1781,325,0.0,0.0,0.0,0.0,0.0,1012.0,661.0,0.0,...,0.0,0.0,19.0,1.0,0.0,0.0,0.0,0.0,267.0,2430
2001,2565,351,0.0,0.0,0.0,0.0,0.0,931.0,710.0,0.0,...,0.0,0.0,22.0,4.0,0.0,0.0,0.0,0.0,407.0,2492
2002,3567,406,0.0,0.0,0.0,0.0,0.0,893.0,836.0,0.0,...,0.0,0.0,12.0,7.0,0.0,0.0,0.0,0.0,454.0,2470
2003,4077,351,0.0,0.0,0.0,0.0,0.0,966.0,962.0,0.0,...,0.0,0.0,2.0,5.0,0.0,0.0,0.0,0.0,454.0,2642
2004,5385,435,0.0,0.0,0.0,0.0,0.0,939.0,1013.0,0.0,...,0.0,0.0,1.0,9.0,0.0,0.0,0.0,0.0,535.0,2919
2005,7191,561,0.0,0.0,0.0,0.0,0.0,943.0,1296.0,0.0,...,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,639.0,3507
2006,9940,780,0.0,0.0,0.0,0.0,0.0,925.0,1526.0,0.0,...,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,757.0,3863
2007,11849,820,0.0,0.0,0.0,0.0,0.0,905.0,1489.0,0.0,...,0.0,0.0,2.0,5.0,0.0,0.0,0.0,0.0,829.0,3906
2008,14586,946,0.0,0.0,0.0,0.0,0.0,715.0,1548.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,922.0,3972
2009,14940,780,0.0,0.0,0.0,0.0,0.0,654.0,1677.0,0.0,...,0.0,0.0,0.0,17.0,0.0,0.0,0.0,0.0,841.0,4159
2010,16540,780,0.0,0.0,0.0,0.0,0.0,577.0,1890.0,0.0,...,0.0,0.0,3.0,26.0,0.0,0.0,0.0,0.0,729.0,4902
2011,20042,946,0.0,0.0,0.0,0.0,0.0,514.0,2308.0,0.0,...,0.0,0.0,0.0,56.0,0.0,0.0,0.0,0.0,853.0,6361
2012,24072,1128,0.0,0.0,0.0,0.0,0.0,630.0,3217.0,0.0,...,0.0,0.0,5.0,94.0,0.0,0.0,645.0,0.0,921.0,11983
2013,29256,1378,5.0,1106.0,7.0,1301.0,3949.0,0.0,0.0,0.0,...,7.0,81.0,0.0,0.0,0.0,0.0,0.0,1092.0,0.0,26219
2014,34599,1596,4.0,82.0,8.0,2243.0,5111.0,0.0,0.0,0.0,...,571.0,53.0,0.0,0.0,0.0,22.0,0.0,1382.0,0.0,44412
2015,38541,1653,0.0,35.0,6.0,2492.0,5236.0,0.0,0.0,0.0,...,569.0,34.0,0.0,0.0,0.0,11.0,0.0,1246.0,0.0,40325
2016,35925,1225,0.0,73.0,14.0,2219.0,2251.0,0.0,0.0,0.0,...,460.0,10.0,0.0,0.0,2.0,0.0,0.0,639.0,0.0,16901
2017,51249,2145,0.0,74.0,8.0,1975.0,4980.0,0.0,0.0,1.0,...,5.0,29.0,0.0,0.0,0.0,1.0,0.0,451.0,0.0,9563
2018,50370,1770,0.0,0.0,8.0,1322.0,4182.0,0.0,0.0,0.0,...,0.0,23.0,0.0,0.0,0.0,415.0,0.0,495.0,0.0,8156

In [26]:
serie_bolsas = bolsas_byYear[['ARTICULADOR PEDAGÓGICO','CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA', 'CÁTEDRA','DOUTORADO PLENO', 'DOUTORADO SANDUÍCHE', 'Doutorado','Doutorado Sanduíche', 'ESCOLA DE ALTOS ESTUDOS', 'ESPECIALIZAÇÃO','ESTÁGIO DOCENTE', 'ESTÁGIO SÊNIOR', 'Especialização', 'Estágio Sênior','GRADUAÇÃO', 'GRADUAÇÃO PLENA', 'GRADUAÇÃO SANDUÍCHE','Graduação Sanduíche', 'MESTRADO', 'MESTRADO PROFISSIONAL','MESTRADO SANDUÍCHE', 'Mestrado', 'Mestrado Sanduíche', 'PIDRH','PROFESSOR/PESQUISADOR VISITANTE','Professor de Educação Básica', 'PÓS-DOUTORADO', 'Pós Doc']]

In [27]:
# export_csv = teste.to_csv (r'export_dataframe_extrangeiro.csv', index = None, header=True)

In [30]:
type(serie_bolsas)

pandas.core.frame.DataFrame

In [33]:
series_extras = serie_bolsas['ARTICULADOR PEDAGÓGICO']
type(series_extras)
# series_extras

pandas.core.series.Series

In [21]:
# doutorado = (serie_bolsas['Doutorado']+serie_bolsas['DOUTORADO PLENO']+serie_bolsas['DOUTORADO SANDUÍCHE'] + serie_bolsas['Doutorado Sanduíche']).to_frame()
# graduacao = (serie_bolsas['GRADUAÇÃO SANDUÍCHE'] + serie_bolsas['Graduação Sanduíche'] + serie_bolsas['GRADUAÇÃO']+serie_bolsas['GRADUAÇÃO PLENA']).to_frame()
# mestrado = (serie_bolsas['MESTRADO PROFISSIONAL']+serie_bolsas['MESTRADO']+serie_bolsas['Mestrado']+serie_bolsas['MESTRADO SANDUÍCHE']+serie_bolsas['Mestrado Sanduíche']).to_frame()
# pos_doc = (serie_bolsas['PÓS-DOUTORADO'] + serie_bolsas['Pós Doc']).to_frame()

In [37]:
doutorado = (serie_bolsas['Doutorado']+serie_bolsas['DOUTORADO PLENO']+serie_bolsas['DOUTORADO SANDUÍCHE'] + serie_bolsas['Doutorado Sanduíche'])
graduacao = (serie_bolsas['GRADUAÇÃO SANDUÍCHE'] + serie_bolsas['Graduação Sanduíche'] + serie_bolsas['GRADUAÇÃO']+serie_bolsas['GRADUAÇÃO PLENA'])
mestrado = (serie_bolsas['MESTRADO PROFISSIONAL']+serie_bolsas['MESTRADO']+serie_bolsas['Mestrado']+serie_bolsas['MESTRADO SANDUÍCHE']+serie_bolsas['Mestrado Sanduíche'])
pos_doc = (serie_bolsas['PÓS-DOUTORADO'] + serie_bolsas['Pós Doc'])

df = pd.DataFrame()
df['GRADUACAO'] = graduacao
df['DOUTORADO'] = doutorado
df['MESTRADO'] = mestrado
df['POS_DOC'] = pos_doc
df['ARTICULADOR PEDAGÓGICO'] = serie_bolsas['ARTICULADOR PEDAGÓGICO']
df['CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA'] = serie_bolsas['CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA']
df['CÁTEDRA'] = serie_bolsas['CÁTEDRA']
df['PIDRH'] = serie_bolsas['PIDRH']
df['PROFESSOR/PESQUISADOR VISITANTE'] = serie_bolsas['PROFESSOR/PESQUISADOR VISITANTE']
df['Professor de Educação Básica'] = serie_bolsas['Professor de Educação Básica']
df_transportada = df.transpose()
df_transportada

Ano,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
GRADUACAO,103.0,344.0,470.0,418.0,268.0,253.0,422.0,622.0,648.0,676.0,...,891.0,1473.0,2446.0,6190.0,17972.0,33991.0,29579.0,10593.0,1668.0,1687.0
DOUTORADO,1480.0,1587.0,1673.0,1641.0,1729.0,1928.0,1952.0,2239.0,2451.0,2394.0,...,2331.0,2467.0,2822.0,3847.0,5250.0,7354.0,7728.0,4470.0,6955.0,5504.0
MESTRADO,18.0,10.0,20.0,26.0,19.0,7.0,10.0,7.0,7.0,7.0,...,17.0,29.0,56.0,99.0,96.0,637.0,611.0,478.0,35.0,23.0
POS_DOC,266.0,256.0,267.0,407.0,454.0,454.0,535.0,639.0,757.0,829.0,...,841.0,729.0,853.0,921.0,1092.0,1382.0,1246.0,639.0,451.0,495.0
ARTICULADOR PEDAGÓGICO,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,5.0,4.0,0.0,0.0,0.0,0.0
CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1106.0,82.0,35.0,73.0,74.0,0.0
CÁTEDRA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,7.0,8.0,6.0,14.0,8.0,8.0
PIDRH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
PROFESSOR/PESQUISADOR VISITANTE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,22.0,11.0,0.0,1.0,415.0
Professor de Educação Básica,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,645.0,0.0,0.0,0.0,0.0,0.0,0.0

In [39]:
export_csv = df_transportada.to_csv (r'extrangeiro_transport.csv', header=True)

        Tipo                                         Quantidade
0  doutorado             0
Ano
1998  1480.0
1999  1...
1  graduacao              0
Ano
1998    103.0
1999...
2   mestrado            0
Ano
1998   18.0
1999   10....
3    pos_doc             0
Ano
1998   266.0
1999   ...

In [47]:
serie_bolsas = teste.sum(skipna = True)

In [48]:
serie_bolsas[['ARTICULADOR PEDAGÓGICO','CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA', 'CÁTEDRA','DOUTORADO PLENO', 'Doutorado', 'ESCOLA DE ALTOS ESTUDOS', 'ESPECIALIZAÇÃO','ESTÁGIO DOCENTE', 'ESTÁGIO SÊNIOR', 'Especialização', 'Estágio Sênior','GRADUAÇÃO', 'GRADUAÇÃO PLENA','MESTRADO PROFISSIONAL', 'PIDRH','PROFESSOR/PESQUISADOR VISITANTE','Professor de Educação Básica']]

ARTICULADOR PEDAGÓGICO                            9.0
CAPACITAÇÃO PROFESSORES DA EDUCAÇÃO BÁSICA     1370.0
CÁTEDRA                                          51.0
DOUTORADO PLENO                               11552.0
Doutorado                                     12780.0
ESCOLA DE ALTOS ESTUDOS                           1.0
ESPECIALIZAÇÃO                                  719.0
ESTÁGIO DOCENTE                                 417.0
ESTÁGIO SÊNIOR                                 2622.0
Especialização                                   68.0
Estágio Sênior                                  680.0
GRADUAÇÃO                                         1.0
GRADUAÇÃO PLENA                                   2.0
MESTRADO PROFISSIONAL                          1612.0
PIDRH                                             2.0
PROFESSOR/PESQUISADOR VISITANTE                 449.0
Professor de Educação Básica                    645.0
dtype: float64

In [50]:
data = [['doutorado',doutorado],['graduacao',graduacao],['mestrado',mestrado],['pos_doc',pos_doc]]
df = pd.DataFrame(data, columns = ['Tipo', 'Quantidade'])

In [51]:
df

        Tipo  Quantidade
0  doutorado     70065.0
1  graduacao    111501.0
2   mestrado      2212.0
3    pos_doc     14435.0